### ISSUE TITLE
大佬可否打个包，不会python一点也不会用啊...

### ISSUE THREAD

**Issue by 1042970366** [Holy-Shine/GitToc#2]
大佬可否打个包，不会python一点也不会用啊...

**Comment by Holy-Shine** [comment]
@1042970366 Hi你好！已经添加了windows PE的支持！GUI程序是gitToc.exe， 可以直接在win下运行啦。

**Comment by 1042970366** [comment]
谢谢谢谢，虽然我已经花了一会时间学会了咋运行使用.py的文件，还是谢谢大佬给打包成exe文件~辛苦啦~




------------------ 原始邮件 ------------------
发件人: "西木野Maki"<notifications@github.com>;
发送时间: 2019年8月27日(星期二) 下午3:36
收件人: "Holy-Shine/GitToc"<GitToc@noreply.github.com>;
抄送: "飞云"<1042970366@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [Holy-Shine/GitToc] 大佬可否打个包，不会python一点也不会用啊... (#2)




@1042970366 Hi你好！已经添加了windows PE的支持！GUI程序是gitToc.exe， 可以直接在win下运行啦。

**Comment by 1042970366** [comment]
> @1042970366 Hi你好！已经添加了windows PE的支持！GUI程序是gitToc.exe， 可以直接在win下运行啦。

大佬辛苦，谢谢大佬~

**Comment by Holy-Shine** [comment]
@1042970366 太客气了！有bug尽管开issue喔 :smile:
