### ISSUE TITLE
代码块缩进消失

### ISSUE THREAD

**Issue by JiaHeng-DLUT** [Holy-Shine/GitToc#3]

**Comment by Holy-Shine** [comment]
@JiaHeng-DLUT Hi～能给我看下消失的代码块的markdown源码吗:smile:

**Comment by JiaHeng-DLUT** [comment]
```
## Test1

```c++
#include <iostream>
using namespace std;

int main() {
    cout << "md" << endl;
    return 0;
}
``\`
```
去掉最后的 `\`

**Comment by Holy-Shine** [comment]
@JiaHeng-DLUT ok.因为这个脚本是检测“#”的，如果代码块里有#，需要把它放到'''   '''包起来的代码块里面，所以你的代码块需要改成
'''c++
\#\# test1
...
...
'''

**Comment by JiaHeng-DLUT** [comment]
但是 `GitHub Flavored Markdown` 并不支持 `'''...'''` 代码块呀

**Comment by Holy-Shine** [comment]
@JiaHeng-DLUT 抱歉打错了，代码块是 \```  ```标准markdown语法的

**Comment by JiaHeng-DLUT** [comment]
@Holy-Shine 抱歉，我没理解要怎么改。我又测试了一下，发现只有一级标题下的代码块转换之后缩进正常，二三四级标题下的代码块的缩进都消失了。

原文档：
![image](https://user-images.githubusercontent.com/33179480/64874795-57df8300-d67e-11e9-8f99-c26a4a1f4195.png)

转换之后：
![image](https://user-images.githubusercontent.com/33179480/64874871-79d90580-d67e-11e9-9e57-32934c296ecc.png)

Markdown 源码如下：

[test.txt](https://github.com/Holy-Shine/GitToc/files/3610720/test.txt)

**Comment by Holy-Shine** [comment]
@JiaHeng-DLUT 确实是代码逻辑的问题，已经在最新的版本里修复了。have a try 😄

**Comment by JiaHeng-DLUT** [comment]
刚刚测试了一下，确实已经修复了呢，点赞👍
