### ISSUE TITLE
二级无序标题的缩进消失

### ISSUE THREAD

**Issue by lzw5399** [Holy-Shine/GitToc#4]
老哥，用的时候发现现在逻辑是会把`除了代码块之外`的每行开始的空格去除。一般情况下是没什么问题的，就是有时候会用到`二级无序标题`，去掉空格会导致其变成`一级无序标题`。如下
```
- 一级无序标题
   - 二级无序标题

+ 一级无序标题
   + 二级无序标题

* 一级无序标题
   * 二级无序标题
```
----
- 一级无序标题
   - 二级无序标题

+ 一级无序标题
   + 二级无序标题

* 一级无序标题
   * 二级无序标题

----

**转换图：**
![](https://tva1.sinaimg.cn/large/007S8ZIlgy1gge5sqsxbfj30sq0a3aao.jpg)

**Comment by Holy-Shine** [comment]
@lzw5399 这次update修复了这个bug，你可以看下

**Comment by lzw5399** [comment]
感谢，刚刚还fork尝试自己改了版 hh
![](https://tva1.sinaimg.cn/large/007S8ZIlgy1gge8jq49f7j30pp0ld41f.jpg)
